### ISSUE TITLE
Add support for ODBC Source

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/lakeapi#91]
Like ROAPI is doing it:

https://roapi.github.io/docs/config/databases.html

**Comment by aersam** [comment]
We would probably need to directly query those tables since DuckDB has no support for reading from relational databases other than Postgres and Sqlite. 

Polars has support for more databases, but no query pushdown, meaning it's not usable for us. 

If we directly query the source we cannot use it in the sql endpoint, or at least not mix it.

**Comment by aersam** [comment]
At a later point we probably want to go for ADBC instead of ODBC and use ADBC driver for ms sql server (which does not exist, yet).

**Comment by aersam** [comment]
For now, probably arrow-odbc is the best option we have to get an arrow dataset
